# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

ccflags-y += -I$(srctree)/drivers/regulator
ccflags-y += -I$(srctree)/drivers/opp

obj-$(CONFIG_AMLOGIC_MESON_CPUFREQ) += amlogic-cpufreq.o
amlogic-cpufreq-y := meson-cpufreq.o
