# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_IRBLASTER) += amlogic-irblaster.o
amlogic-irblaster-y := core.o
amlogic-irblaster-y += sysfs.o
amlogic-irblaster-y += irblaster-meson.o
