# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_S4) += amlogic-pinctrl-soc-s4.o
amlogic-pinctrl-soc-s4-y := pinctrl-meson-s4.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_C2) += amlogic-pinctrl-soc-c2.o
amlogic-pinctrl-soc-c2-y := pinctrl-meson-c2.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_C3) += amlogic-pinctrl-soc-c3.o
amlogic-pinctrl-soc-c3-y := pinctrl-meson-c3.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_A1) += amlogic-pinctrl-soc-a1.o
amlogic-pinctrl-soc-a1-y := pinctrl-meson-a1.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_SC2) += amlogic-pinctrl-soc-sc2.o
amlogic-pinctrl-soc-sc2-y := pinctrl-meson-sc2.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T3) += amlogic-pinctrl-soc-t3.o
amlogic-pinctrl-soc-t3-y := pinctrl-meson-t3.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T7) += amlogic-pinctrl-soc-t7.o
amlogic-pinctrl-soc-t7-y := pinctrl-meson-t7.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T5M) += amlogic-pinctrl-soc-t5m.o
amlogic-pinctrl-soc-t5m-y := pinctrl-meson-t5m.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_G12A) += amlogic-pinctrl-soc-g12a.o
amlogic-pinctrl-soc-g12a-y := pinctrl-meson-g12a.o
