# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)/drivers

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON) += pinctrl-meson.o pinctrl-meson-axg-pmx.o

obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_S4) += pinctrl-meson-s4.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_C2) += pinctrl-meson-c2.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_C3) += pinctrl-meson-c3.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_A1) += pinctrl-meson-a1.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_SC2) += pinctrl-meson-sc2.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T3) += pinctrl-meson-t3.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T7) += pinctrl-meson-t7.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_T5M) += pinctrl-meson-t5m.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_G12A) += pinctrl-meson-g12a.o
