# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_SPI_MESON_SPICC) += spi-meson-spicc.o
obj-$(CONFIG_AMLOGIC_SPI_MESON_SPIFC) += spi-meson-spifc.o
obj-$(CONFIG_AMLOGIC_SPI_MESON_SPIFC_V2) += spi-meson-spifc-v2.o
obj-$(CONFIG_AMLOGIC_SPI_MESON_SPICC_SLAVE) += spi-meson-spicc-slave.o vmem.o
