# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) += amlogic-crypto-dma.o
amlogic-crypto-dma-y := aml-dma.o aml-crypto-dma.o aml-aes-dma.o aml-sha-dma.o aml-crypto-device.o

obj-$(CONFIG_CRYPTO_DES) += aml-tdes-dma.o
