# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_PM) += amlogic-pm.o
amlogic-pm-y := main.o
amlogic-pm-$(CONFIG_AMLOGIC_GX_SUSPEND) += gx_pm.o
amlogic-pm-$(CONFIG_AMLOGIC_GX_REBOOT) += reboot.o
