# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_AMLOGIC_MESON_IR) += meson_ir.o

meson_ir-y += meson_ir_core.o \
	meson_ir_main.o \
	meson_ir_sysfs.o \
	meson_ir_cdev.o \
	meson_ir_raw.o \
	meson_ir_regmap.o \
	meson_ir_decoder_xmp.o