# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_RTC) = amlogic-rtc.o
amlogic-rtc-y := main.o
amlogic-rtc-$(CONFIG_AMLOGIC_RTC_DRV_MESON_VRTC) += rtc-meson-vrtc.o
amlogic-rtc-$(CONFIG_AMLOGIC_MESON_RTC) += meson-rtc.o