# Overlays for the Bananapi CM5

dtbo-y += i2c4.dtbo \
	i2c5.dtbo \
	uart3.dtbo \
	uart3_rts_cts.dtbo \
	uart4.dtbo \
	uart4_rts_cts.dtbo \
	spi2.dtbo \
	pwm_f.dtbo \
	otg-host.dtbo \
	otg-device.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
