# SPDX-License-Identifier: GPL-2.0-only
# Amlogic pcie drivers

ccflags-y += -I$(srctree)/drivers/pci/controller/dwc

obj-$(CONFIG_AMLOGIC_PCIE_V2_HOST) += amlogic_pcie_v2_host.o
amlogic_pcie_v2_host-y := amlogic-pcie-v2-host.o
