# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AMLOGIC_MTD_SPI_NAND) += amlogic-spinand.o
amlogic-spinand-y := spinand.o
amlogic-spinand-y += core.o
amlogic-spinand-y += gigadevice.o
amlogic-spinand-y += macronix.o
amlogic-spinand-y += micron.o
amlogic-spinand-y += paragon.o
amlogic-spinand-y += toshiba.o
amlogic-spinand-y += winbond.o
amlogic-spinand-y += meson_spinand.o
amlogic-spinand-y += spi-meson-mem.o
