# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AMLOGIC_MTD_SPI_NAND) += amlogic_spinand.o
amlogic_spinand-objs := core.o gigadevice.o macronix.o micron.o paragon.o toshiba.o winbond.o meson_spinand.o spi-meson-mem.o
