# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_FREERTOS) += amlogic-freertos.o
amlogic-freertos-y := freertos.o

obj-$(CONFIG_AMLOGIC_AUTO_CAPTURE) += amlogic-autocapture.o
amlogic-autocapture-y := free_reserved.o
