# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

KASAN_SANITIZE_dmc_monitor.o := n

obj-$(CONFIG_AMLOGIC_DDR_TOOL)	+= ddr_tool.o ddr_port_desc.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH) += ddr_bandwidth.o ddr_priority.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GXL) += ddr_band_op_gxl.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GXL) += ddr_band_op_gxl.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GX) += ddr_band_op_gx.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_G12) += ddr_band_op_g12.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_A1) += ddr_band_op_a1.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T5) += ddr_band_op_t5.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T7) += ddr_band_op_t7.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_S4) += ddr_band_op_s4.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_S5) += ddr_band_op_s5.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_C3) += ddr_band_op_c3.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T5M) += ddr_band_op_t5m.o

obj-$(CONFIG_AMLOGIC_DMC_MONITOR) += dmc_monitor.o dmc_port_sub.o
obj-$(CONFIG_AMLOGIC_DMC_DEV_ACCESS) += dmc_dev_access.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_G12)	+= dmc_g12.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_TM2)	+= dmc_tm2.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_GX) += dmc_gx.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_C1) += dmc_c1.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_T7) += dmc_t7.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_S4) += dmc_s4.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_S5) += dmc_s5.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_C2) += dmc_c2.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_C3) += dmc_c3.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_T5M)	+= dmc_t5m.o
