# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_POWER) += amlogic-power.o
amlogic-power-y := main.o
amlogic-power-y += power_domain_sysfs.o
amlogic-power-y += sec_pwr_ctrl.o
amlogic-power-y += sec_power_domain.o
amlogic-power-y += power_ee_domain.o
