# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

ccflags-y += -I$(srctree)/drivers/thermal

obj-$(CONFIG_AMLOGIC_AMLOGIC_THERMAL) += meson_tsensor.o
obj-$(CONFIG_AMLOGIC_COOLDEV) += meson_cooldev.o cpu_hotplug.o
obj-$(CONFIG_AMLOGIC_CPUCORE_THERMAL) += cpucore_cooling.o
obj-$(CONFIG_AMLOGIC_GPU_THERMAL) += gpu_cooling.o
obj-$(CONFIG_AMLOGIC_GPUCORE_THERMAL) += gpucore_cooling.o
obj-$(CONFIG_AMLOGIC_DDR_THERMAL) += ddr_cooling.o
