# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_SECMON) += amlogic-secmon.o
amlogic-secmon-y := main.o
amlogic-secmon-y += secmon.o
amlogic-secmon-$(CONFIG_AMLOGIC_DOLBY_FW) += dolby_fw.o
