# SPDX-License-Identifier: GPL-2.0
dtb-y += kvim4.dtb
dtb-y += kvim4n.dtb
dtb-y += kvim1s.dtb
dtb-y += bananapi_cm5io.dtb
dtb-y += bananapi_rpicm4io.dtb

subdir-y += overlays/bananapi_cm5io
subdir-y += overlays/bananapi_rpicm4io
subdir-y += overlays/kvim4n

clean-files := *.dtb
