# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_MTD_NAND) += amlogic_mtd_nfc.o
amlogic_mtd_nfc-y := meson_nand.o
amlogic_mtd_nfc-y += meson_parse_part.o
amlogic_mtd_nfc-y += nand_flash_id.o
