# SPDX-License-Identifier: (GPL-2.0+ OR MIT)



obj-$(CONFIG_AMLOGIC_MTD_COMMON) += amlogic-mtd-common.o
amlogic-mtd-common-y := nand_bootpart.o
amlogic-mtd-common-$(CONFIG_AMLOGIC_MTD_RESV) += rsv-manage.o
amlogic-mtd-common-$(CONFIG_AMLOGIC_MTD_RESV) += rsv-dev.o
amlogic-mtd-common-$(CONFIG_AMLOGIC_MTD_RESV) += rsv-key.o
