# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_MESON_SARADC) += amlogic-adc.o
amlogic-adc-y := meson_saradc.o
amlogic-adc-y += meson_saradc_c2.o
amlogic-adc-y += meson_saradc_m8.o
amlogic-adc-$(CONFIG_AMLOGIC_IIO_KFIFO_BUF) += kfifo_buf.o
