# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_EFUSE_UNIFYKEY) += efuse_unifykey.o
obj-$(CONFIG_AMLOGIC_EFUSE) += efuse.o efuse_api.o
obj-$(CONFIG_AMLOGIC_EFUSE_BURN) +=  efuse_burn.o
obj-$(CONFIG_AMLOGIC_UNIFYKEY) += security_key.o unifykey.o unifykey_dts.o storage_key.o normal_key.o
obj-$(CONFIG_AMLOGIC_DEFENDKEY) += defendkey.o securekey.o
