# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_EFUSE_UNIFYKEY) += amlogic-efuse-unifykey.o
amlogic-efuse-unifykey-y := efuse_unifykey.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_EFUSE) += efuse.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_EFUSE) += efuse_api.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_EFUSE_BURN) += efuse_burn.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_UNIFYKEY) += security_key.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_UNIFYKEY) += unifykey.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_UNIFYKEY) += unifykey_dts.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_UNIFYKEY) += storage_key.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_UNIFYKEY) += normal_key.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_DEFENDKEY) += defendkey.o
amlogic-efuse-unifykey-$(CONFIG_AMLOGIC_DEFENDKEY) += securekey.o
