# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_RESET_MESON) += amlogic-reset.o
amlogic-reset-y := main.o
amlogic-reset-y += reset-meson.o
amlogic-reset-$(CONFIG_AMLOGIC_DOS_RESET_MESON) += reset-meson-dos.o
