# SPDX-License-Identifier: GPL-2.0-only
# Amlogic clock drivers

ccflags-y += -I$(srctree)/drivers/amlogic/clk/meson

obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_AO_CLKC) += meson-aoclk.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_CPU_DYNDIV) += clk-cpu-dyndiv.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_DUALDIV) += clk-dualdiv.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_EE_CLKC) += meson-eeclk.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_MPLL) += clk-mpll.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_PHASE) += clk-phase.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_PLL) += clk-pll.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_REGMAP) += clk-regmap.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_SCLK_DIV) += sclk-div.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_MESON_VID_PLL_DIV) += vid-pll-div.o
obj-$(CONFIG_AMLOGIC_MESON_CLK_MEASURE) += meson-clk-measure.o
obj-$(CONFIG_AMLOGIC_CLK_DEBUG) += meson-clk-debug.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_S4) += s4.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_SC2) += sc2.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_C2) += c2.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_C3) += c3.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_A1) += a1.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_T3) += t3.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_T7) += t7.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_T5M) += t5m.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_G12A) += g12a.o
obj-$(CONFIG_AMLOGIC_COMMON_CLK_G12A) += g12a-aoclk.o
