# Overlays for the Bananapi CM5

dtbo-y += i2c5.dtbo \
	uart4.dtbo \
	spi2.dtbo \
	spi2_flash.dtbo \
	pwm_h.dtbo \
	pwm_h_beeper.dtbo \
	i2smic.dtbo \
	otg-host.dtbo \
	otg-device.dtbo \
	hifi_pcm5122.dtbo \
	waveshare_tft35c.dtbo \
	onewire.dtbo \
	can0.dtbo \
	spdifout.dtbo


targets += $(dtbo-y)
always  := $(dtbo-y)
