# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

# Makefile for hifi4dsp

obj-$(CONFIG_AMLOGIC_HIFI4DSP) += amlogic-hifidsp.o
amlogic-hifidsp-y := hifi4dsp_module.o
amlogic-hifidsp-y += hifi4dsp_firmware.o
amlogic-hifidsp-y += hifi4dsp_dsp.o
amlogic-hifidsp-y += dsp_top.o
amlogic-hifidsp-y += hifi4dsp_syslog.o
