# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/drivers/usb/host/

obj-$(CONFIG_AMLOGIC_CRG) += crg.o
obj-$(CONFIG_AMLOGIC_CRG) += crg_drd.o
obj-$(CONFIG_AMLOGIC_CRG) += crg_udc.o
obj-$(CONFIG_AMLOGIC_CRG) += crg_usbphy.o
