dtbo-y += i2c2.dtbo \
	i2c3.dtbo \
	uart2.dtbo \
	spi0.dtbo \
	spi0_flash.dtbo \
	pwm_cd.dtbo \
	pwm_cd-c.dtbo \
	pwm_c-beeper.dtbo \
	pwm_ef-f.dtbo \
	i2smic.dtbo \
	pdmmic.dtbo \
	ds3231.dtbo \
	hifi_pcm5102a.dtbo \
	hifi_pcm5122.dtbo \
	waveshare_tft24_lcd.dtbo \
	waveshare_tft35c_lcd.dtbo \
	waveshare_tft35c_rtp.dtbo \
	waveshare_hdmi35_tp.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
