# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_MEMORY_DEBUG) += memory_ext/
obj-$(CONFIG_AMLOGIC_MEMORY_DEBUG) += reg_access/
obj-$(CONFIG_AMLOGIC_MEMORY_DEBUG) += ddr_tool/
obj-$(CONFIG_AMLOGIC_MEMORY_DEBUG) += ramdump/
