# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

ccflags-y += -I$(srctree)/drivers/mmc/core

obj-$(CONFIG_AMLOGIC_MMC_MESON_GX) += amlogic-mmc.o
amlogic-mmc-y := meson-gx-mmc.o
amlogic-mmc-y += mmc_dtb.o
amlogic-mmc-y += mmc_key.o
