# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-usb2.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-usb.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-usb3.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-otg-v2.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-otg.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-m31-usb2.o
obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-m31-usb3.o
