# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AMLOGIC_CRG) += phy-aml-crg-drd-usb2.o \
			phy-aml-crg-drd-usb.o \
			phy-aml-crg-drd-usb3.o \
			phy-aml-crg-drd-otg-v2.o \
			phy-aml-crg-drd-otg.o \
			phy-aml-m31-usb2.o \
			phy-aml-m31-usb3.o
